# Generated by Django 3.0.7 on 2020-07-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripplr', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
