# Generated by Django 3.0.7 on 2020-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripplr', '0005_customgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='id',
        ),
        migrations.AddField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customgroup',
            name='first_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customgroup',
            name='password',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customgroup',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
